In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
train_data = pd.read_csv(r'G:\Data Sets\Dont Overfit\DO_train.csv')

In [4]:
test_data = pd.read_csv('G:\Data Sets\Dont Overfit\DO_test.csv')

In [5]:
train_data.head()

,id,target,0,1,2,3,4,5,6,7,...,290,291,292,293,294,295,296,297,298,299
0,0,1.0,-0.098,2.165,0.681,-0.614,1.309,-0.455,-0.236,0.276,...,0.867,1.347,0.504,-0.649,0.672,-2.097,1.051,-0.414,1.038,-1.065
1,1,0.0,1.081,-0.973,-0.383,0.326,-0.428,0.317,1.172,0.352,...,-0.165,-1.695,-1.257,1.359,-0.808,-1.624,-0.458,-1.099,-0.936,0.973
2,2,1.0,-0.523,-0.089,-0.348,0.148,-0.022,0.404,-0.023,-0.172,...,0.013,0.263,-1.222,0.726,1.444,-1.165,-1.544,0.004,0.800,-1.211
3,3,1.0,0.067,-0.021,0.392,-1.637,-0.446,-0.725,-1.035,0.834,...,-0.404,0.640,-0.595,-0.966,0.900,0.467,-0.562,-0.254,-0.533,0.238
4,4,1.0,2.347,-0.831,0.511,-0.021,1.225,1.594,0.585,1.509,...,0.898,0.134,2.415,-0.996,-1.006,1.378,1.246,1.478,0.428,0.253

In [7]:
train_data.isnull().sum()

id        0
target    0
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
         ..
270       0
271       0
272       0
273       0
274       0
275       0
276       0
277       0
278       0
279       0
280       0
281       0
282       0
283       0
284       0
285       0
286       0
287       0
288       0
289       0
290       0
291       0
292       0
293       0
294       0
295       0
296       0
297       0
298       0
299       0
Length: 302, dtype: int64

In [8]:
train_data.describe()

,id,target,0,1,2,3,4,5,6,7,...,290,291,292,293,294,295,296,297,298,299
count,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,...,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000
mean,124.500000,0.640000,0.023292,-0.026872,0.167404,0.001904,0.001588,-0.007304,0.032052,0.078412,...,0.044652,0.126344,0.018436,-0.012092,-0.065720,-0.106112,0.046472,0.006452,0.009372,-0.128952
std,72.312977,0.480963,0.998354,1.009314,1.021709,1.011751,1.035411,0.955700,1.006657,0.939731,...,1.011416,0.972567,0.954229,0.960630,1.057414,1.038389,0.967661,0.998984,1.008099,0.971219
min,0.000000,0.000000,-2.319000,-2.931000,-2.477000,-2.359000,-2.566000,-2.845000,-2.976000,-3.444000,...,-2.804000,-2.443000,-2.757000,-2.466000,-3.287000,-3.072000,-2.634000,-2.776000,-3.211000,-3.500000
25%,62.250000,0.000000,-0.644750,-0.739750,-0.425250,-0.686500,-0.659000,-0.643750,-0.675000,-0.550750,...,-0.617000,-0.510500,-0.535750,-0.657000,-0.818500,-0.821000,-0.605500,-0.751250,-0.550000,-0.754250
50%,124.500000,1.000000,-0.015500,0.057000,0.184000,-0.016500,-0.023000,0.037500,0.060500,0.183500,...,0.067500,0.091000,0.057500,-0.021000,-0.009000,-0.079500,0.009500,0.005500,-0.009000,-0.132500
75%,186.750000,1.000000,0.677000,0.620750,0.805000,0.720000,0.735000,0.660500,0.783250,0.766250,...,0.797250,0.804250,0.631500,0.650250,0.739500,0.493000,0.683000,0.794250,0.654250,0.503250
max,249.000000,1.000000,2.567000,2.419000,3.392000,2.771000,2.901000,2.793000,2.546000,2.846000,...,2.865000,2.801000,2.736000,2.596000,2.226000,3.131000,3.236000,2.626000,3.530000,2.771000

In [36]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold,RepeatedStratifiedKFold
from catboost import CatBoostClassifier

In [12]:
X_train = train_data.drop(['id', 'target'], axis=1)
y_train = train_data['target']
X_test = test_data.drop(['id'], axis=1)
n_fold = 20
folds = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=42)
repeated_folds = RepeatedStratifiedKFold(n_splits=20, n_repeats=20, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score,precision_score,accuracy_score,recall_score,roc_auc_score

In [32]:
def train_model(X, X_test, y, params, folds=folds, model_type='lgb', plot_feature_importance=False, averaging='usual', model=None):
    oof = np.zeros(len(X))
    prediction = np.zeros(len(X_test))
    scores = []
    feature_importance = pd.DataFrame()
    for fold_n, (train_index, valid_index) in enumerate(folds.split(X, y)):
        # print('Fold', fold_n, 'started at', time.ctime())
        X_train, X_valid = X[train_index], X[valid_index]
        y_train, y_valid = y[train_index], y[valid_index]
        
        if model_type == 'lgb':
            train_data = lgb.Dataset(X_train, label=y_train)
            valid_data = lgb.Dataset(X_valid, label=y_valid)
            
            model = lgb.train(params,
                    train_data,
                    num_boost_round=2000,
                    valid_sets = [train_data, valid_data],
                    verbose_eval=500,
                    early_stopping_rounds = 200)
            
            y_pred_valid = model.predict(X_valid)
            y_pred = model.predict(X_test, num_iteration=model.best_iteration_)
            
        if model_type == 'xgb':
            train_data = xgb.DMatrix(data=X_train, label=y_train, feature_names=X_tr.columns)
            valid_data = xgb.DMatrix(data=X_valid, label=y_valid, feature_names=X_tr.columns)

            watchlist = [(train_data, 'train'), (valid_data, 'valid_data')]
            model = xgb.train(dtrain=train_data, num_boost_round=20000, evals=watchlist, early_stopping_rounds=200, verbose_eval=500, params=params)
            y_pred_valid = model.predict(xgb.DMatrix(X_valid, feature_names=X_tr.columns), ntree_limit=model.best_ntree_limit)
            y_pred = model.predict(xgb.DMatrix(X_test, feature_names=X_tr.columns), ntree_limit=model.best_ntree_limit)
        
        if model_type == 'cat':
            model = CatBoostClassifier(iterations=20000,  eval_metric='AUC', **params)
            model.fit(X_train, y_train, eval_set=(X_valid, y_valid), cat_features=[], use_best_model=True, verbose=False)

            y_pred_valid = model.predict(X_valid)
            y_pred = model.predict(X_test)
            
            
        if model_type == 'sklearn':
            model = model
            model.fit(X_train, y_train)
            y_pred_valid = model.predict(X_valid).reshape(-1,)
            score = roc_auc_score(y_valid, y_pred_valid)
            # print(f'Fold {fold_n}. AUC: {score:.4f}.')
            # print('')
            
            y_pred = model.predict_proba(X_test)[:, 1]
            
        if model_type == 'glm':
            model = sm.GLM(y_train, X_train, family=sm.families.Binomial())
            model_results = model.fit()
            model_results.predict(X_test)
            y_pred_valid = model_results.predict(X_valid).reshape(-1,)
            score = roc_auc_score(y_valid, y_pred_valid)
            
            y_pred = model_results.predict(X_test)
        
        oof[valid_index] = y_pred_valid.reshape(-1,)
        scores.append(roc_auc_score(y_valid, y_pred_valid))

        if averaging == 'usual':
            prediction += y_pred
        elif averaging == 'rank':
            prediction += pd.Series(y_pred).rank().values  
        
        if model_type == 'lgb':
            # feature importance
            fold_importance = pd.DataFrame()
            fold_importance["feature"] = X.columns
            fold_importance["importance"] = model.feature_importances_
            fold_importance["fold"] = fold_n + 1
            feature_importance = pd.concat([feature_importance, fold_importance], axis=0)

    prediction /= n_fold
    
    print('CV mean score: {0:.4f}, std: {1:.4f}.'.format(np.mean(scores), np.std(scores)))
    
    if model_type == 'lgb':
        feature_importance["importance"] /= n_fold
        if plot_feature_importance:
            cols = feature_importance[["feature", "importance"]].groupby("feature").mean().sort_values(
                by="importance", ascending=False)[:50].index

            best_features = feature_importance.loc[feature_importance.feature.isin(cols)]

            plt.figure(figsize=(16, 12));
            sns.barplot(x="importance", y="feature", data=best_features.sort_values(by="importance", ascending=False));
            plt.title('LGB Features (avg over folds)');
        
            return oof, prediction, feature_importance
        return oof, prediction, scores
    
    else:
        return oof, prediction, scores

In [34]:
log_reg = LogisticRegression(solver='liblinear',C = 0.1, class_weight='balanced')
oof_lr, prediction_lr, scores = train_model(X_train, X_test, y_train, params=None, model_type='sklearn', model=log_reg)

CV mean score: 0.6875, std: 0.1461.

In [37]:
cat_params = {'learning_rate': 0.02,
              'depth': 5,
              'l2_leaf_reg': 10,
              'bootstrap_type': 'Bernoulli',
              #'metric_period': 500,
              'od_type': 'Iter',
              'od_wait': 50,
              'random_seed': 11,
              'allow_writing_files': False}
oof_lr, prediction_lr, scores = train_model(X_train, X_test, y_train, params=cat_params, model_type='cat')

CV mean score: 0.5494, std: 0.0807.

In [38]:
model = CatBoostClassifier(iterations=400,  eval_metric='AUC', **cat_params)
model.fit(X_train, y_train, cat_features=[], use_best_model=True, verbose=200)

You should provide test set for use best model. use_best_model parameter has been switched to false value.

0:	total: 47ms	remaining: 18.8s
200:	total: 7.49s	remaining: 7.42s
399:	total: 15.1s	remaining: 0us

In [40]:
model =LogisticRegression(class_weight='balanced', penalty='l1', C=0.1, solver='liblinear')
oof_lr, prediction_lr_repeated, scores = train_model(X_train, X_test, y_train, params=None, model_type='sklearn', model=model, folds=repeated_folds)

CV mean score: 0.7138, std: 0.1209.

In [41]:
ans = pd.Series(prediction_lr_repeated)

In [42]:
ans

0        13.409388
1         9.718502
2        10.325979
3        15.135727
4         8.857907
5         6.265891
6         7.426943
7         4.720140
8        14.091718
9         4.549624
10       10.562489
11        6.729413
12        6.808834
13       13.203898
14        5.153992
15       14.016808
16        7.267877
17       14.429672
18        8.572298
19        6.199918
20        8.735856
21       13.863955
22        9.457548
23        6.870695
24        7.049657
25       12.352461
26        1.555692
27       15.223240
28       13.414164
29       11.694656
           ...
19720     5.537528
19721    15.552764
19722    10.628118
19723     3.565819
19724    14.022983
19725     8.854902
19726    14.892491
19727     9.199375
19728    11.112456
19729    16.878402
19730     6.472292
19731     3.384248
19732    11.372317
19733     6.231714
19734    11.579955
19735     7.865148
19736    13.605193
19737    12.523472
19738    12.645615
19739     6.800596
19740    10.385845
19741    12.328292
19742     9.010731
19743     2.493930
19744    16.028263
19745    10.780803
19746    18.009376
19747     6.259106
19748    15.587264
19749     5.154609
Length: 19750, dtype: float64

In [43]:
df = pd.DataFrame(test_data['id'] , columns=['id'])

In [44]:
df['target'] = ans

In [45]:
df

          id     target
0        250  13.409388
1        251   9.718502
2        252  10.325979
3        253  15.135727
4        254   8.857907
5        255   6.265891
6        256   7.426943
7        257   4.720140
8        258  14.091718
9        259   4.549624
10       260  10.562489
11       261   6.729413
12       262   6.808834
13       263  13.203898
14       264   5.153992
15       265  14.016808
16       266   7.267877
17       267  14.429672
18       268   8.572298
19       269   6.199918
20       270   8.735856
21       271  13.863955
22       272   9.457548
23       273   6.870695
24       274   7.049657
25       275  12.352461
26       276   1.555692
27       277  15.223240
28       278  13.414164
29       279  11.694656
...      ...        ...
19720  19970   5.537528
19721  19971  15.552764
19722  19972  10.628118
19723  19973   3.565819
19724  19974  14.022983
19725  19975   8.854902
19726  19976  14.892491
19727  19977   9.199375
19728  19978  11.112456
19729  19979  16.878402
19730  19980   6.472292
19731  19981   3.384248
19732  19982  11.372317
19733  19983   6.231714
19734  19984  11.579955
19735  19985   7.865148
19736  19986  13.605193
19737  19987  12.523472
19738  19988  12.645615
19739  19989   6.800596
19740  19990  10.385845
19741  19991  12.328292
19742  19992   9.010731
19743  19993   2.493930
19744  19994  16.028263
19745  19995  10.780803
19746  19996  18.009376
19747  19997   6.259106
19748  19998  15.587264
19749  19999   5.154609

[19750 rows x 2 columns]

In [46]:
df.to_csv('G:\Data Sets\Dont Overfit\sol1.csv' , index  = False)